/**
 * Created by Administrator on 2018/3/12.
 */
(function(){
    angular.module('app',['ui.router','app.controllers','app.directives','app.services','app.filters'])
        .config(function($stateProvider,$urlRouterProvider){
            $stateProvider
                .state('control',{
                    url:'/control',
                    templateUrl:'view/control.html',
                    controller:'controllerController'
                })
                .state('user',{
                    url:'/user',
                    templateUrl:'view/user.html',
                    controller:'userController'
                })
                .state('scenery',{
                    url:'/scenery',
                    templateUrl:'view/scenery.html',
                    controller:'sceneryController'
                })
                .state('sceneryDetail',{
                    url:'/sceneryDetail',
                    templateUrl:'view/sceneryDetail.html',
                    controller:'sceneryDetailController',
                    params:{'id':null}
                })
                .state('addScenery',{
                    url:'/addScenery',
                    templateUrl:'view/addScenery.html',
                    controller:'addSceneryController'
                })
                .state('editScenery',{
                    url:'/editScenery',
                    templateUrl:'view/editScenery.html',
                    controller:'editSceneryController',
                    params:{id:null}
                })
                .state('hotel',{
                    url:'/hotel',
                    templateUrl:'view/hotel.html',
                    controller:'hotelController'
                })
                .state('hotelDetail',{
                    url:'/hotelDetail',
                    templateUrl:'view/hotelDetail.html',
                    controller:'hotelDetailController',
                    params:{'id':null}
                })
                .state('addHotel',{
                    url:'/addHotel',
                    templateUrl:'view/addHotel.html',
                    controller:'addHotelController',
                    params:{'id':null}
                })
                .state('editHotel',{
                    url:'/editHotel',
                    templateUrl:'view/editHotel.html',
                    controller:'editHotelController',
                    params:{'id':null}
                })
                .state('route',{
                    url:'/route',
                    templateUrl:'view/route.html',
                    controller:'routeController'
                })
                .state('addRoute',{
                    url:'/addRoute',
                    templateUrl:'view/addRoute.html',
                    controller:'addRouteController'
                })
                .state('plan',{
                    url:'/plan',
                    templateUrl:'view/plan.html',
                    controller:'planController',
                    params:{'id':null,'name':null,'provinceId':null}
                })
                .state('order',{
                    url:'/order',
                    templateUrl:'view/order.html',
                    controller:'orderController',
                    params:{'id':null}
                })

                .state('viewpoint',{
                    url:'/viewpoint',
                    templateUrl:'view/viewpoint.html',
                    controller:'viewpointController'
                });
            $urlRouterProvider.otherwise('control');
        });
})();